### ISSUE TITLE
Images not choose

### ISSUE THREAD

**Issue by JavaPalash** [ard333/TextureClassification-GLCM-NB#1]
Hello Sir,
My self Palash Hinglaspurkar I am doing a academic project to detect the breast cancer. so I need to get the features from the images my project Is also on swing so.
I downloaded your project "texture-classification-glcm-nb" its successfully run it but, when I choose the training data its shows me the dialogue box  that no valid training data can you please me for this..

**Comment by ard333** [comment]
"There are no valid training data..." happend when all file names in choosed directory are 
not match with pattern in MainController [line 112](https://github.com/ard333/texture-classification-glcm-nb/blob/master/src/main/java/com/ard333/textureclassification/glcmnb/controller/MainController.java#L112).
Moreover, you can check line [116](https://github.com/ard333/texture-classification-glcm-nb/blob/master/src/main/java/com/ard333/textureclassification/glcmnb/controller/MainController.java#L116) and [118](https://github.com/ard333/texture-classification-glcm-nb/blob/master/src/main/java/com/ard333/textureclassification/glcmnb/controller/MainController.java#L118) for further conditions.

**Comment by JavaPalash** [comment]
I just give a one breast cancer image with the name as
"Banign1.jpg"
  And what should i give input in test data?

Thanks and regards

Palash Hinglaspurkar

**Comment by ard333** [comment]
You can try Banign.1.jpg
And make sure the number is match to the order in [TextureClass](https://github.com/ard333/texture-classification-glcm-nb/blob/master/src/main/java/com/ard333/textureclassification/glcmnb/model/TextureClass.java).

For example, mine is
`Wood, Brick, Fur, Plaid`
so, Wood should be 1, Brick should be 2, and so on.

**Comment by JavaPalash** [comment]
Its taken the image by name Banign.1.jpg
but now what i passed in test data?

when i passed the same image in test its shown me an error

**Comment by ard333** [comment]
Whats error?

**Comment by JavaPalash** [comment]
What should i pass in testing section?
This is now a question.

when i pass the same image that i pass in training section its shown me an
error
"Arrayindxoutofboundexception" in MainController.java line number 160

**Comment by ard333** [comment]
I think your value in TextureClass and the number in file name in is not match.

Please re-check my comment here
https://github.com/ard333/texture-classification-glcm-nb/issues/1#issuecomment-486186851

or can you show me all training data file name and the value in TextureClass?

**Comment by JavaPalash** [comment]
OK Just Check the data I have breast cancer images Such as Benign,Malign
and normal images. and texture class also find the attached document

**Comment by ard333** [comment]
Then just set in TextureClass
`Benign, Malign, Normal`


and for the file name, for example

yourfirstbenignimagename.1.jpg
yoursecondtbenignimagename.1.jpg
blablablawhatever.1.jpg
.
.
yourfirstmalignimagename.2.jpg
yoursecondmalignimagename.2.jpg
blablablawhatever.2.jpg
.
.
yourfirstnormalimagename.3.jpg
yoursecondnormalimagename.3.jpg
blablablawhatever.3.jpg

**Comment by JavaPalash** [comment]
Hello,
I done with this but its shown an error again please find the attached
ducuments.
Steps:
1. I'll passed the Benign.1.jpg, Benign.2.jpg, Benign.3.jpg As a Training
data
2 When I passed the Normal.1.jpg, Normal.2.jpg, Normal3.jpg its shown an
error as you seen in the  utilited4 image..!!!

If you are free can you see this by remotely by using TeamViewer?

Palash Hinglaspurkar

**Comment by JavaPalash** [comment]
Normal.1.jpg, Normal.2.jpg and Normal.3.jpg I passed as a Testing data but
its shown an error..!!
Palash Hinglaspurkar

**Comment by ard333** [comment]
No, you are wrong, end of file name is index of class in TextureClass

If you do this
Benign.1.jpg, Benign.2.jpg, Benign.3.jpg, **Benign.4.jpg**
of course, there is no class 4, because the class is just 3
`Benign, Malign, Normal`

You can set file name like this for first class
Benign.1.1.jpg, Benign.2.1.jpg, Benign.3.1.jpg, Benign.4.1.jpg, whatever.1.jpg, whatever123.1.jpg
Malign.1.jpg <- this will also be considered class 1 (Benign) because end with .1

Please check again my comment
https://github.com/ard333/texture-classification-glcm-nb/issues/1#issuecomment-486186851
https://github.com/ard333/texture-classification-glcm-nb/issues/1#issuecomment-486545293

**Comment by JavaPalash** [comment]
Ok Now i'll Pass
Training Data:
Beningn1.1.jpg,
Malign1.2.jpg,
Normal1.3.jpg
Its Taken the images Now

What shoul ill pass into the Testing Data...?
Normal1.3.jpg, Normal2.3.jpg? Or something else?

Very Few changes are needed now Please help
Palash Hinglaspurkar

**Comment by ard333** [comment]
There is no special pattern for test data file name

**Comment by JavaPalash** [comment]
Ok Now i'll Pass The
Beningn1.1.jpg
Beningn2.1.jpg
Beningn3.1.jpg
Malign1.2.jpg
Malign3.2.jpg
As a training data

And
Normal1.3.jpg
Normal2.3.jpg
Normal3.3.jpg

What next how get the features its shows nothing console and what is the
next step?
to complete the project

Please find the attachment

Palash Hinglaspurkar

**Comment by JavaPalash** [comment]
Hello Sir Please help

Palash Hinglaspurkar

**Comment by ard333** [comment]
Sorry I'm quite busy, you can upload your dataset, I will check it later.

**Comment by JavaPalash** [comment]
Ok I send you my dataset and please let me know..
Please find the below attached document.


Palash Hinglaspurkar

**Comment by JavaPalash** [comment]
Any Update Sir..?
Palash Hinglaspurkar

**Comment by ard333** [comment]
I can't find any attachment, I create simple dataset for test my code again, because the link for texture database is dead. You can test using [this dataset](https://drive.google.com/file/d/1s5EhPsFfNYchULRyMhVC716CLDvyzX2Y/view?usp=sharing).

**Comment by JavaPalash** [comment]
I test with the dataset you given me!!!!
I'll send you  the output screen and tell me what it means and what next
...!!!
Is it compare the features of trained and test and give the class result
related to images.?

i.e. As in output you can see that "whatever1.png => class result=> Beningn
its shows" and "whatever2.png => class result => malign its shows"

Palash Hinglaspurkar

**Comment by ard333** [comment]
Yes, it is very clearly written in the readme.
Texture Classification using **Naive Bayes** and **GLCM for feature extraction**

**Comment by JavaPalash** [comment]
What next program is in waiting means still runs is it completed?

its not displaying features but its internally compare the features of
trained and test right?
and if features is match its shows the class result that perticular image
file is belongs to perticular class ?

**Comment by ard333** [comment]
> What next program is in waiting means still runs is it completed?

Yes is it completed.

> its not displaying features

You can just write some code for your particular needs.

> but its internally compare the features of
trained and test right?

Yes, it's classified using Naive Bayes

> and if features is match its shows the class result that perticular image
file is belongs to perticular class ?

It's classified using Naive Bayes.

**Comment by JavaPalash** [comment]
Thank you very much for your help...

One last question is...

I have breast cancer effected and non-effected images.. That I am passed in
trained and test as a data.
So from this code is it possible to come in conclusion that the particular
image has a breast cancer or not?

Palash Hinglaspurkar

**Comment by ard333** [comment]
For the possibility, I can't immediately give a conclusion, it depends on your data and your case, whether it is suitable or not if using glcm and naive bayes.

**Comment by JavaPalash** [comment]
ok thanks
